version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      cron: "0 16 * * 5"
      timezone: "Europe/Berlin"
    assignees:
      - "novusvetus"
    reviewers:
      - "novusvetus"
    labels:
      - "maintenance"
      - "dependencies"
    open-pull-requests-limit: 10
