name: Sync labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/labels.yml
  pull_request:
    paths:
      - .github/labels.yml
      - .github/workflows/labels.yml
  schedule:
    - cron: "0 7 * * 5"

permissions:
  contents: read
  issues: write

jobs:
  labels:
    name: ♻️ Sync labels
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: 🚀 Run Label Syncer
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          dry-run: ${{ github.event_name == 'pull_request' }}
