name: Sponsors labels

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  labels:
    name: 💖️ Sponsors labels
    runs-on: ubuntu-latest
    steps:
      - name: 💖️ Check sponsors labels
        uses: JasonEtco/is-sponsor-label-action@v2
        with:
          label: "sponsor 💖"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
